name: Spins & Stress Pull Request

on: [pull_request]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up PATH
        run: |
          echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Install Android Build Tools
        run: sdkmanager "build-tools;30.0.1"
      - name: Build Spins & Stress
        run: ./gradlew deploy
      - name: Upload Spins & Stress jar
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }} Pull Request
          path: build/libs/${{ github.event.repository.name }}.jar
